CREATE TABLE member (
	MEMBER_NUM	NUMBER(10,0)		NOT NULL,
	ID	VARCHAR2(100 BYTE)		NOT NULL,
	PASSWORD	VARCHAR2(200 BYTE)		NULL,
	NAME	VARCHAR2(15 BYTE)		NULL,
	EMAIL	VARCHAR2(30 BYTE)		NULL,
	GENDER	VARCHAR2(15 BYTE)		NULL,
	SIGN_UP_DATE	DATE		NULL
);

CREATE TABLE vehicles_owned (
	VIN	VARCHAR2(18 BYTE)		NULL,
	CAR_MODEL	VARCHAR2(30 BYTE)		NULL,
	MEMBER_NUM	NUMBER(10,0)		NOT NULL
);

CREATE TABLE order_history (
	ORDER_NUM	NUMBER(20,0)		NOT NULL,
	ORDER_TIME	DATE		NULL,
	ORDER_STATUS	CHAR(1)		NULL,
	VIN	VARCHAR2(18 BYTE)		NULL,
	MEMBER_NUM	NUMBER(10,0)		NOT NULL,
	FEATURES_NUM	NUMBER(10,0)		NOT NULL
);

CREATE TABLE car_features (
	FEATURES_NUM	NUMBER(10,0)		NOT NULL,
	FEATURES_NAME	VARCHAR2(100 BYTE)		NULL,
	SUPPORTED_CAR_MODEL	VARCHAR2(30 BYTE)		NULL,
	PRICE	NUMBER(10,2)		NULL
);

CREATE TABLE sw_version (
	SW_NAME	VARCHAR2(30 BYTE)		NULL,
	LATEST_VERSION	VARCHAR2(30 BYTE)		NULL
);

ALTER TABLE member ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEMBER_NUM
);

ALTER TABLE vehicles_owned ADD CONSTRAINT PK_VEHICLES_OWNED PRIMARY KEY (
	VIN
);

ALTER TABLE order_history ADD CONSTRAINT PK_ORDER_HISTORY PRIMARY KEY (
	ORDER_NUM
);

ALTER TABLE car_features ADD CONSTRAINT PK_CAR_FEATURES PRIMARY KEY (
	FEATURES_NUM
);

ALTER TABLE sw_version ADD CONSTRAINT PK_SW_VERSION PRIMARY KEY (
	SW_NAME
);
/*
DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE JOB_HISTORY CASCADE CONSTRAINTS;
DROP TABLE JOBS CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE REGIONS CASCADE CONSTRAINTS;
*/

INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (1, 'user01', 'pass01', '강하늘', 'sky@test.com', 'Male', SYSDATE-100);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (2, 'user02', 'pass02', '이민정', 'mj@test.com', 'Female', SYSDATE-90);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (3, 'user03', 'pass03', '박서준', 'sj@test.com', 'Male', SYSDATE-80);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (4, 'user04', 'pass04', '김태리', 'tr@test.com', 'Female', SYSDATE-70);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (5, 'user05', 'pass05', '최우식', 'ws@test.com', 'Male', SYSDATE-60);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (6, 'user06', 'pass06', '한소희', 'sh@test.com', 'Female', SYSDATE-50);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (7, 'user07', 'pass07', '정해인', 'hi@test.com', 'Male', SYSDATE-40);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (8, 'user08', 'pass08', '임윤아', 'ya@test.com', 'Female', SYSDATE-30);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (9, 'user09', 'pass09', '공유', 'gy@test.com', 'Male', SYSDATE-20);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (10, 'user10', 'pass10', '송혜교', 'hk@test.com', 'Female', SYSDATE-10);
INSERT INTO member (MEMBER_NUM, ID, PASSWORD, NAME, EMAIL, GENDER, SIGN_UP_DATE) VALUES (11, 'user11', 'pass10', '김도원', 'dk@test.com', 'Male', SYSDATE-10);
--SELECT * FROM MEMBER;


-- 17자리 규격에 맞춘 차대번호 데이터 입력
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KMHJM511KP123456', 'GV80', 1);   -- 현대(KMH), 2019년식(K)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KNAJP812LR234567', 'IONIQ5', 2); -- 기아(KNA), 2020년식(L)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KNAKU413MR345678', 'EV6', 3);    -- 기아(KNA), 2021년식(M)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KMHGN511NP456789', 'G80', 4);    -- 현대(KMH), 2022년식(N)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KMHRC511PP567890', 'K9', 5);     -- 현대(KMH), 2023년식(P)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('5YJ3E1EBBR678901', 'MODEL3', 6); -- 테슬라(5YJ), 2024년식(R)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('5YJYGDEEBR789012', 'MODELY', 7); -- 테슬라(5YJ), 2024년식(R)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('WPOAA2Y1SR890123', 'TAYCAN', 8); -- 포르쉐(WPO), 2024년식(R)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('WBA31AK0SR901234', 'X5', 9);     -- BMW(WBA), 2024년식(R)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('W1KEE1EBBR012345', 'EQS', 10);    -- 벤츠(W1K), 2024년식(R)
INSERT INTO vehicles_owned (VIN, CAR_MODEL, MEMBER_NUM) VALUES ('KMHRA511SR123456', 'CASPER', 11); -- 현대(KMH), 2025년식(K)

--SELECT * FROM vehicles_owned;

INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (101, 'HDA2 (Highway Drive)', 'GV80', 15000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (102, 'V2L (Vehicle to Load)', 'IONIQ5', 8000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (103, 'Remote Smart Parking', 'EV6', 12000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (104, 'Augmented Reality Nav', 'G80', 6000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (105, 'Rear Seat Entertainment', 'K9', 25000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (106, 'Full Self-Driving (Beta)', 'MODEL3', 9000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (107, 'Premium Connectivity', 'MODELY', 1500);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (108, 'Performance Battery Plus', 'TAYCAN', 5000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (109, 'Laser Light Upgrade', 'X5', 2000);
INSERT INTO car_features (FEATURES_NUM, FEATURES_NAME, SUPPORTED_CAR_MODEL, PRICE) VALUES (110, 'Hyperscreen Theme Pack', 'EQS', 4500);

--SELECT * FROM car_features;

INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1001, SYSDATE-5, 'C', 'KMHJM511KP123456', 1, 101);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1002, SYSDATE-4, 'C', 'KNAJP812LR234567', 2, 102);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1003, SYSDATE-3, 'P', 'KNAKU413MR345678', 3, 103);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1004, SYSDATE-2, 'C', 'KMHGN511NP456789', 4, 104);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1005, SYSDATE-1, 'F', 'KMHRC511PP567890', 5, 105);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1006, SYSDATE, 'C', '5YJ3E1EBBR678901', 6, 106);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1007, SYSDATE, 'C', '5YJYGDEEBR789012', 7, 107);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1008, SYSDATE, 'C', 'WPOAA2Y1SR890123', 8, 108);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1009, SYSDATE, 'P', 'WBA31AK0SR901234', 9, 109);
INSERT INTO order_history (ORDER_NUM, ORDER_TIME, ORDER_STATUS, VIN, MEMBER_NUM, FEATURES_NUM) VALUES (1010, SYSDATE, 'C', 'W1KEE1EBBR012345', 10, 110);

--SELECT * FROM order_history;


INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Engine_Control_Unit', 'v1.4.2');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Infotainment_OS', 'v12.0.5');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('ADAS_Module', 'v2.1.0');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Battery_Management', 'v3.0.1');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Telematics_Unit', 'v1.1.9');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Airbag_Controller', 'v1.0.4');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Body_Control_Unit', 'v2.2.3');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Chassis_Module', 'v4.1.0');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Climate_Control', 'v1.5.0');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Interior_Lighting', 'v1.0.2');
INSERT INTO sw_version (SW_NAME, LATEST_VERSION) VALUES ('Navigation', 'v2.5.6');

--SELECT * FROM sw_version;
COMMIT;

-- car_features 테이블에 컬럼 추가
ALTER TABLE car_features ADD (LAST_UPDATED DATE);

-- sw_version 테이블에 컬럼 추가
ALTER TABLE sw_version ADD (LAST_UPDATED DATE);

-- car_features: 각 기능별로 1~10번 멤버의 가입일을 하나씩 매칭
UPDATE car_features f
SET LAST_UPDATED = (
    SELECT m.SIGN_UP_DATE + 5 
    FROM member m 
    WHERE m.MEMBER_NUM = (f.FEATURES_NUM - 100) -- 101번 기능은 1번 멤버 날짜 사용
);

-- sw_version: 최신 SW 순서대로 최근 가입자 날짜 매칭
UPDATE sw_version 
SET LAST_UPDATED = (SELECT MAX(SIGN_UP_DATE) FROM member);

SELECT * FROM car_features;
SELECT * FROM sw_version;
COMMIT;

INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (111, 'High Beam Assist', 150, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (112, 'Digital Key 2.0', 200, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (113, 'Remote Smart Parking', 350, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (114, 'Built-in Cam 2', 250, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (115, 'Rear Seat Entertainment', 500, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (116, 'Augmented Reality Nav', 180, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (117, 'Active Road Noise Control', 300, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (118, 'Dynamic Welcome Light', 120, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (119, 'Intelligent Speed Limit', 100, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (120, 'Remote Camera View', 90, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (121, 'Smart Tailgate Plus', 130, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (122, 'Advanced Air Purifier', 70, 'GV80');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (123, 'Highway Driving Assist 2', 400, 'GV80');

COMMIT;

--SELECT * FROM car_features;

UPDATE CAR_FEATURES
SET LAST_UPDATED = SYSDATE
WHERE LAST_UPDATED IS NULL;


CREATE SEQUENCE seq_order START WITH 1 INCREMENT BY 1;
COMMIT;

-- 테스트를 위해 해당 차량의 구매 이력을 모두 삭제 (모든 기능이 목록에 뜨게 됨)
DELETE FROM ORDER_HISTORY WHERE VIN = 'KMHJM511KP123456';

COMMIT;

-- 캐스퍼 전용 엔터테인먼트 및 편의 기능 (201~215)
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (201, 'Casper Welcome Sound', 30, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (202, 'Active Sound Design', 50, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (203, 'Theme Selection UI', 40, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (204, 'Remote Climate Control', 120, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (205, 'Heated Steering Wheel', 80, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (206, 'Digital Key Mobile', 150, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (207, 'Built-in Dash Cam', 180, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (208, 'Advanced Safety Package', 250, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (209, 'Parking Distance Warning', 90, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (210, 'Mood Lighting Plus', 60, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (211, 'Streaming Service UI', 25, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (212, 'Voice Recognition Plus', 45, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (213, 'Cargo Management Kit', 55, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (214, 'Camping Mode Power', 100, 'CASPER');
INSERT INTO CAR_FEATURES (FEATURES_NUM, FEATURES_NAME, PRICE, SUPPORTED_CAR_MODEL) VALUES (215, 'Navigation Auto Map', 75, 'CASPER');

COMMIT;

-- 마지막 업데이트 날짜 갱신
UPDATE CAR_FEATURES
SET LAST_UPDATED = SYSDATE
WHERE SUPPORTED_CAR_MODEL = 'CASPER';

-- 테스트를 위해 해당 차량의 구매 이력을 모두 삭제 (모든 기능이 목록에 뜨게 됨)
DELETE FROM ORDER_HISTORY WHERE VIN = 'KMHRA511SR123456';

COMMIT;
